### ISSUE TITLE
segfaults as soon as it joins the server

### ISSUE THREAD

**Issue by manen** [azalea-rs/azalea#214]
1.21.5 tried both papermc and vanilla server
using latest commit
rust toolchain: `rustup default nightly-2025-03-01-x86_64` (it would be nice if the readme made it clear which nightly it'll 100% work with)

code:

```rs
use azalea::{prelude::Component, swarm::SwarmBuilder, Account, Client, ClientBuilder, Event};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
	println!("Hello, world!");

	let account = Account::offline("fasz");

	ClientBuilder::new()
		.set_handler(handle)
		.start(account, "127.0.0.1")
		.await?;
}

#[derive(Default, Clone, bevy_ecs_macros::Component)]
pub struct State;

async fn handle(bot: Client, event: Event, state: State) -> anyhow::Result<()> {
	match event {
		Event::Chat(m) => bot.chat(&m.content()),
		event => println!("{event:?}"),
	}
	Ok(())
}
```

debugger:

![Image](https://github.com/user-attachments/assets/2456b2d8-3d21-4ec4-a41f-7ebb16409ca4)

![Image](https://github.com/user-attachments/assets/6c06e19f-7d0f-4ad9-b0ba-8d6d79041d8a)

console output (incoming packets):
https://pastebin.com/AHGziKnm

**Comment by mat-1** [comment]
Thanks for the detailed report :)

That's an odd issue... My guess is that the executable got corrupted somehow? The error at least doesn't seem to be azalea's fault since the segfault is in bevy_ecs. Could you try running `cargo clean` and compiling again?

By the way, the recommended nightly version is just whatever the latest is (that's what the CI uses). It might be worth updating your nightly version too in case it was a bug in the Rust compiler.

**Comment by manen** [comment]
using nigthly 2025-04-11 i can't even get it to compile

this is why i was using the older nightly, i looked it up but no other solutions worked

```
error: crate `azalea_entity` required to be available in rlib format, but was not found in this form
```


```
error: linking with `cc` failed: exit status: 1
  |
  = note:  "cc" "-m64" "/tmp/rustcunDQ71/symbols.o" "<257 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/mnt/hdd/dev/gang/target/debug/deps/{libanyhow-eee0032c520aff90.rlib,libazalea-cbfdc7271ef3517c.rlib,libnum_format-0393d20d95076272.rlib,libarrayvec-a2b5b1cd6af46bc5.rlib,libazalea_client-3c8c26c10748a0f0.rlib,libbevy_log-fcd2f89ff500e9c0.rlib,libtracing_subscriber-b48f35bf824f80a1.rlib,libsharded_slab-8157ec80bc003edc.rlib,libmatchers-1da3603608fba3ae.rlib,libregex_automata-819405320f4ff8f7.rlib,libregex_syntax-f001b8f76713d51e.rlib,libregex-248fa60a9283f3c1.rlib,libregex_automata-0f6c68fd7b33d984.rlib,libaho_corasick-c731e6c6881e0ef8.rlib,libregex_syntax-cc3bb52c2edcb09f.rlib,libnu_ansi_term-d9b76d34e361f05d.rlib,liboverload-704f8e6cc7a057d2.rlib,libtracing_log-21221792cc119008.rlib,libminecraft_folder_path-13200c8e5205aa6a.rlib,libbevy_time-3d32429e6ddd84fc.rlib,libazalea_protocol-c247d9fbfe36bda9.rlib,libazalea_brigadier-27404b1dff0a92a4.rlib,libhickory_resolver-5acacd2b377df659.rlib,libmoka-8bff82c8a5ea8dec.rlib,libtagptr-96677e7c2d56d260.rlib,libcrossbeam_epoch-ce407c22bd0f1532.rlib,libcrossbeam_channel-a968240841725057.rlib,libhickory_proto-d1a02a1b32a4eaba.rlib,librand-e601b6d8c5fb490f.rlib,librand_chacha-b8c68a8f095eb3ac.rlib,librand_core-453b460f48e41b56.rlib,libgetrandom-f428aa4918ecd14c.rlib,libdata_encoding-c78005e1b3b1d87c.rlib,libtinyvec-19f836a1b19d9b4d.rlib,libtinyvec_macros-dae4282b78017f08.rlib,libtokio_util-474dfebf47f64df6.rlib,libfutures-3cd4ac6c4a9169b6.rlib,libfutures_executor-049769b9051f06d0.rlib,libflate2-da7c9c1c976fd522.rlib,libminiz_oxide-52521104e5db234d.rlib,libadler2-75be1f4fe4448802.rlib,liblibz_rs_sys-9dcbe427163f8de9.rlib,libzlib_rs-df4299cd090deb31.rlib,libcrc32fast-e6fc96e3e3e886b2.rlib,libsocks5_impl-da857c72898201f2.rlib,libazalea_physics-ac8cb224a901a258.rlib,libazalea_entity-968e97660c23e848.rlib,libbevy_app-781e4967867d4a50.rlib,libctrlc-542e762f32278630.rlib,libnix-cfc9b45ede8fc821.rlib,libazalea_world-94950a43b7122045.rlib,librustc_hash-dc45a8d11cf191ca.rlib,libazalea_block-32aed3c2acbc4f0b.rlib,libderive_more-abea1d6df6306df6.rlib,libazalea_inventory-61f5e27d5e5a076a.rlib,libazalea_core-9eba080aa5db2161.rlib,libnohash_hasher-02ec1b16758de256.rlib,libazalea_chat-de9e65c996d46d70.rlib,libazalea_language-b3b110a9a83faf50.rlib,libcompact_str-9ca1bbd7b4a9438f.rlib,libstatic_assertions-b23f9456d08c2faf.rlib,libcastaway-1e9f32733e3d0c07.rlib,libazalea_registry-81c76ff142c70ffd.rlib,libparking_lot-96344711d46ee2e7.rlib,libparking_lot_core-5f06cd33afb0bc74.rlib,liblock_api-521d5ebdbdf632e7.rlib,libscopeguard-cfa69166bd4da734.rlib,libbevy_ecs-41084cc4ecd8e7e6.rlib,libbitflags-b602eb1a3e38c567.rlib,libnonmax-b91f9da84f828705.rlib,libdisqualified-97207d8ed0b23fc8.rlib,libpetgraph-3523e5d02e8224ff.rlib,libindexmap-1ae00f2ae3dbe18b.rlib,libequivalent-3ff77df1ac69f53a.rlib,libhashbrown-3dbf1660ac3601c7.rlib,libfixedbitset-b209c621e5c171f6.rlib,libbevy_tasks-1110c322d5255cc9.rlib,libasync_channel-9e7a4e7e84a24319.rlib,libevent_listener_strategy-31ceef034ba0abd3.rlib,libevent_listener-ca680a37c0758df8.rlib,libasync_executor-062d6a4b4680f01f.rlib,libfutures_lite-b91d6ca7b5b41307.rlib,libparking-a94712ad990739b0.rlib,libfastrand-ecdbacb34276294a.rlib,libconcurrent_queue-ba8c246484e4de4e.rlib,libcrossbeam_utils-d823c1be33549f73.rlib,libasync_task-fe618d2b503885ad.rlib,libfixedbitset-55733227a194804b.rlib,libbevy_reflect-559bd8462232e367.rlib,libsmol_str-a55272d2af7c4442.rlib,liberased_serde-913617a53290535b.rlib,libtypeid-5cfc49068f6260ce.rlib,libdowncast_rs-c30328866f4bc8af.rlib,libderive_more-34ff34385e593d1c.rlib,libbevy_ptr-8cffebb52c7b866f.rlib,libbevy_utils-2e4547a2e730c7dd.rlib,libhashbrown-a5b4927dafdf9fc1.rlib,liballocator_api2-302c8aaff85fe901.rlib,libahash-ae522cfc7afd666e.rlib,libzerocopy-f02b6ff2c54033ef.rlib,libthread_local-3b751f70c4db9aec.rlib,libazalea_auth-c1924303c2c77ade.rlib,libazalea_crypto-f43bfa8a4fa33c7a.rlib,libcfb8-c2a13a78942b6923.rlib,librsa_public_encrypt_pkcs1-fe1abb67516c3bf5.rlib,libsimple_asn1-980da8f1831c66ce.rlib,libthiserror-95a524d3eeb78b71.rlib,libnum-921bf7f2c2217087.rlib,libnum_rational-1fe8ab8886497f99.rlib,libnum_complex-922fdb1e1eccd990.rlib,libnum_bigint-6c76e6018f79752d.rlib,libsha1-6a744e45d261c51b.rlib,libaes-df66135ea9c5e7d3.rlib,libcipher-9ccf6788617a1d64.rlib,libinout-ea53a4619e26af96.rlib,libreqwest-e8a6bd528f1f2420.rlib,libserde_urlencoded-c78a6280b7a26f2b.rlib,librustls_pemfile-c5c54b28e8143f42.rlib,libipnet-feafdee40f8485a4.rlib,libhyper_rustls-8043fae5afb796aa.rlib,libwebpki_roots-93483b12a088dd0f.rlib,libtokio_rustls-67a8ff67d6e7839d.rlib,librustls-afa05294272b1348.rlib,libwebpki-af277842fffada0e.rlib,libring-2fb2ffc0184839a4.rlib,libuntrusted-9c1a8c0c452596ad.rlib,librustls_pki_types-7d874eb22d2a85ea.rlib,libtower-2c255c82df650119.rlib,libsync_wrapper-045efc56da79a2f9.rlib,libtower_layer-0e51d86a089d8d0f.rlib,libhyper_util-e5ad6a03f1ef8122.rlib,libtower_service-7ac5165b203ec039.rlib,libhyper-5b9553012318e808.rlib,libwant-f9d31a371fafc8ca.rlib,libtry_lock-a3a646dfcf7a7db3.rlib,libhttparse-97246cbd98486692.rlib,libfutures_util-7f0d52ec6b82a9d7.rlib,libfutures_io-da0fe9cd9746e7ba.rlib,libslab-a44c4d15e23f26eb.rlib,libfutures_channel-c1305e37684445b9.rlib,libfutures_sink-2d042891822421e3.rlib,libfutures_task-4ef15010b2e9d7d1.rlib,libpin_utils-37754fca158c29e2.rlib,libhttp_body_util-b0ba32eae9a4394a.rlib,libfutures_core-470cbcc4e13830ab.rlib,libhttp_body-0b0738741886c953.rlib,liblog-e4c872c580f67c43.rlib,liburl-21189b687d5985f9.rlib,libidna-78a08bbd2cca5be1.rlib,libidna_adapter-d86947953dc88871.rlib,libicu_normalizer-a115507432f0d2d8.rlib,libicu_normalizer_data-be2465a2251fcc75.rlib,libwrite16-e2fa00becbd7c062.rlib,libutf8_iter-f95c390134f4cbfc.rlib,libutf16_iter-3678c16489503be9.rlib,libicu_properties-73f9c511876a40db.rlib,libicu_properties_data-24b47e6a8c9fc988.rlib,libicu_locid_transform-fc0ff2276fb0aa6e.rlib,libicu_locid_transform_data-40b8cca0079f7685.rlib,libicu_collections-0878330759e3e68b.rlib,libicu_provider-728c349e720ba58d.rlib,libicu_locid-96f4ad9f202ab2e9.rlib,liblitemap-f6d6367042098f85.rlib,libtinystr-6dd43be9ec976f55.rlib,libzerovec-ca11ea940eb22c80.rlib,libwriteable-5aa6f6f2f089cfaa.rlib,libyoke-d5bc13d4de78de60.rlib,libzerofrom-7caf6ca7c7208c33.rlib,libstable_deref_trait-90b5e60074edf875.rlib,libform_urlencoded-5755bb4947df7437.rlib,libpercent_encoding-e078da13996065cd.rlib,libhttp-f9142bb39d188d33.rlib,libfnv-b4193684a965a7e4.rlib,libazalea_buf-4e2990cb300fe2a2.rlib,libsimdnbt-1e5c6362188462d9.rlib,libsimd_cesu8-3eca04759c7b6ff3.rlib,libsimdutf8-becba7e5ff79e00e.rlib,libbyteorder-855e27c29408f102.rlib,librsa-2b4b4600b1e2771f.rlib,libsha2-3083356109701a11.rlib,libcpufeatures-241f523369765f8e.rlib,libpkcs1-ff0237c4e54b0e7f.rlib,libpkcs8-e600190670b1cc27.rlib,libspki-9d38dec87e5afafe.rlib,libder-44410f06f8b45dbe.rlib,libpem_rfc7468-a4667230d05437f8.rlib,libbase64ct-634e4329702e6f7e.rlib,libsubtle-a7c30e9150b6c9d8.rlib,libsignature-f3936ae65a876414.rlib,libnum_bigint_dig-6ff0879b5e42543c.rlib,liblibm-dcc738406b6cd16b.rlib,libnum_iter-ac1d4f23258e034c.rlib,librand-4cf402448cb983b4.rlib,librand_chacha-cc28a7f006ecf1ae.rlib,libppv_lite86-6d5f4fecc189d1ee.rlib,libzerocopy-73792cef1f38b040.rlib,librand_core-d046cc6f3064f9f2.rlib,libzeroize-172f0b1b1ddf513d.rlib,libnum_integer-1ea5dd72c3718315.rlib,liblazy_static-0aaf5a8a1ab41e5d.rlib,libspin-263d67f202a8f6bf.rlib,libsmallvec-ef3eb687a37fe9fe.rlib,libbase64-abef1adde3530447.rlib,libtokio-fa7a6cda8183d9d8.rlib,libsocket2-32be827b2988deb2.rlib,libbytes-f7b2d9fb270a13e4.rlib,libmio-61fc7f7b8243df6c.rlib,libuuid-0142b1a19db22cc0.rlib,libgetrandom-0317dac52cfc9481.rlib,liblibc-4e79d55609f5748e.rlib,libmd5-ff9c0b4fa3bfbac1.rlib,libcfg_if-19fd298186487766.rlib,libdigest-a8d08b8a94c5905c.rlib,libconst_oid-a054b1acfb7a9345.rlib,libblock_buffer-3633fdf76aafcf56.rlib,libcrypto_common-f7f5870877dcc8ea.rlib,libgeneric_array-fa6c728e5d26ce6f.rlib,libtypenum-b271f6b9fc8fd90d.rlib,libtracing-3506973a25bbd574.rlib,libpin_project_lite-8ceaaa5d1655a324.rlib,libtracing_core-da51973e7197fcb9.rlib,libonce_cell-bef2b7475c636660.rlib,libportable_atomic-37c530fbd51d4c99.rlib,libthiserror-2b734ac5f6e1811e.rlib,libserde_json-b4bbcf32c384ad6f.rlib,libmemchr-08a87d79b356b15c.rlib,libitoa-a586594d020aa48a.rlib,libryu-675674a647ff1eb1.rlib,libchrono-d1b6e16dec6b4067.rlib,libnum_traits-ed901d300e632aa5.rlib,libserde-82d55e746991700c.rlib}.rlib" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib/{libstd-*,libpanic_unwind-*,libobject-*,libmemchr-*,libaddr2line-*,libgimli-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libminiz_oxide-*,libadler2-*,libunwind-*,libcfg_if-*,liblibc-*,liballoc-*,librustc_std_workspace_core-*,libcore-*,libcompiler_builtins-*}.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-L" "/tmp/rustcunDQ71/raw-dylibs" "-B<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld" "-fuse-ld=lld" "-Wl,-znostart-stop-gc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/mnt/hdd/dev/gang/target/debug/build/ring-721a054ea78a90a9/out" "-L" "<sysroot>/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/mnt/hdd/dev/gang/target/debug/deps/client-aea34f3b6a4028a3" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: rust-lld: error: /mnt/hdd/dev/gang/target/debug/deps/libazalea_entity-968e97660c23e848.rlib: unknown file type
          collect2: error: ld returned 1 exit status
```

(it works in release mode for some reason)

**Comment by mat-1** [comment]
This is almost certainly a Rust compiler bug then. :(

It kind of sucks that it's failing in the way it is instead of giving a proper Internal Compiler Error since that'd probably make it easier to debug.

I can't reproduce the issue on my setup which means it might be Windows-only. From some quick searches in the [Rust repo](https://github.com/rust-lang/rust/issues) I can't find anything similar so I think you may have to create a new issue there...

**Comment by manen** [comment]
alright thanks for the responses! it's great to see this project in good hands:)

**Comment by manen** [comment]
i'm running into deadlocks

```
1 deadlocks detected
Deadlock #0
Thread Id 139859695806144
   0:     0x55e32695dad3 - parking_lot_core::parking_lot::deadlock_impl::on_unpark::h1ced1ce9eb487e29
   1:     0x55e32695b30b - parking_lot::raw_mutex::RawMutex::lock_slow::heb3cbd0df0d24854
   2:     0x55e326204c34 - azalea_client::client::Client::position::h6b4ddc4d56056186
   3:     0x55e326204d31 - azalea_client::client::Client::eye_position::h8ae6f5f237f1b7eb
   4:     0x55e325ff78d2 - client::modules::mine::mine_specific::hda8a60b8b7214696
   5:     0x55e325f9ae6f - client::swarm_handler::{{closure}}::ha5a8671d5ca44ed1
   6:     0x55e325f154a1 - tokio::runtime::task::core::Core<T,S>::poll::h300d871827b2ba63
   7:     0x55e325f2b8df - tokio::runtime::task::harness::Harness<T,S>::poll::h7a4fecb441384756
   8:     0x55e326c22e03 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h3952a92904c4a9dd
   9:     0x55e326c22390 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h95227fb5c9de70af
  10:     0x55e326c38221 - tokio::runtime::context::runtime::enter_runtime::hddda06b6411a2f69
  11:     0x55e326c21b5b - tokio::runtime::scheduler::multi_thread::worker::run::h24298ad031e66c5d
  12:     0x55e326c2d936 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::hdf7c803ea711bb0f
  13:     0x55e326c29557 - tokio::runtime::task::core::Core<T,S>::poll::hf06ddc3696b55fd5
  14:     0x55e326c16721 - tokio::runtime::task::harness::Harness<T,S>::poll::h3b14f3776564f417
  15:     0x55e326c1aa7a - tokio::runtime::blocking::pool::Inner::run::hc125b5eb9421fe28
  16:     0x55e326c37240 - std::sys::backtrace::__rust_begin_short_backtrace::h0d2d6b49ecfef855
  17:     0x55e326c35532 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h06ff0b5f7b31402a
  18:     0x55e326c84a8b - std::sys::pal::unix::thread::Thread::new::thread_start::h2da8c9397976689b
  19:     0x7f339f8561f5 - <unknown>
  20:     0x7f339f8d689c - <unknown>
  21:                0x0 - <unknown>

Thread Id 139859676870336
   0:     0x55e32695dad3 - parking_lot_core::parking_lot::deadlock_impl::on_unpark::h1ced1ce9eb487e29
   1:     0x55e32695a44f - parking_lot::raw_rwlock::RawRwLock::wait_for_readers::he2ed8bbcf2d55675
   2:     0x55e326959089 - parking_lot::raw_rwlock::RawRwLock::lock_exclusive_slow::h6aa7b6592dfa4c0a
   3:     0x55e326803d1b - azalea_entity::plugin::indexing::update_entity_chunk_positions::hd1e88cc8787c5ebe
   4:     0x55e3267ffcb4 - <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe::h553f45af60e84e4c
   5:     0x55e326a00a2a - bevy_ecs::schedule::executor::__rust_begin_short_backtrace::run_unsafe::h3fdb507f0800a782
   6:     0x55e3269debc6 - <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run::hf38f54f371b41905
   7:     0x55e32685160d - bevy_ecs::world::World::try_schedule_scope::h6affa3fc23b1bec6
   8:     0x55e3268506cf - bevy_ecs::world::World::resource_scope::h3d86837e3d8b2f80
   9:     0x55e326852081 - <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run::h0810638fb0c6afeb
  10:     0x55e326a00a5a - bevy_ecs::schedule::executor::__rust_begin_short_backtrace::run::hedda64c9237c274c
  11:     0x55e3269deba5 - <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run::hf38f54f371b41905
  12:     0x55e3261cf28d - bevy_ecs::world::World::run_schedule::hb58520f9eaa25de0
  13:     0x55e32612be06 - azalea_client::client::run_schedule_loop::{{closure}}::h727df031c4b36764
  14:     0x55e326129bc4 - tokio::runtime::task::core::Core<T,S>::poll::hb26169dab9451b0a
  15:     0x55e32618401f - tokio::runtime::task::raw::poll::h66dfda44de0c0fbf
  16:     0x55e326c22e03 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h3952a92904c4a9dd
  17:     0x55e326c22390 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h95227fb5c9de70af
  18:     0x55e326c38221 - tokio::runtime::context::runtime::enter_runtime::hddda06b6411a2f69
  19:     0x55e326c21b5b - tokio::runtime::scheduler::multi_thread::worker::run::h24298ad031e66c5d
  20:     0x55e326c2d936 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::hdf7c803ea711bb0f
  21:     0x55e326c29557 - tokio::runtime::task::core::Core<T,S>::poll::hf06ddc3696b55fd5
  22:     0x55e326c16721 - tokio::runtime::task::harness::Harness<T,S>::poll::h3b14f3776564f417
  23:     0x55e326c1aa7a - tokio::runtime::blocking::pool::Inner::run::hc125b5eb9421fe28
  24:     0x55e326c37240 - std::sys::backtrace::__rust_begin_short_backtrace::h0d2d6b49ecfef855
  25:     0x55e326c35532 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h06ff0b5f7b31402a
  26:     0x55e326c84a8b - std::sys::pal::unix::thread::Thread::new::thread_start::h2da8c9397976689b
  27:     0x7f339f8561f5 - <unknown>
  28:     0x7f339f8d689c - <unknown>
  29:                0x0 - <unknown>
```

client::modules::mine::mine_specific:

```rs
fn mine_specific<I: IntoIterator<Item = BlockState>>(swarm: Swarm, states: I) {
  let mut occupied = vec![];

  let states = states.into_iter();
  let states = BlockStates {
    set: states.collect(),
  };

  for bot in swarm.into_iter() {
    let pos = {
      let world = bot.world();
      let world = world.read();
      let mut blocks = world.find_blocks(bot.eye_position(), &states);

      let block = loop {
        match blocks.next() {
          Some(pos) => {
            if !occupied.contains(&pos) {
              occupied.push(pos);
              break Some(pos);
            }
          }
          None => break None,
        }
      };
      block
    };
    tokio::spawn(async move {
      if let Some(pos) = pos {
        bot.goto(RadiusGoal {
          pos: pos.center(),
          radius: 3.5,
        });

        while bot.position().distance_to(&pos.center()) > 4.0 {}
        bot.look_at(pos.center());
        bot.mine(pos).await;
      }
    });
  }
}
```

to be real i don't even know what a deadlock is and why this happens but all the bots just stop moving and get kicked

**Comment by mat-1** [comment]
A deadlock is when you lock a Mutex or RwLock (using either .lock(), .read(), or .write()) twice in a way that causes it to get stuck forever. You can do this by having the second lock happen before the first lock is released (assuming both locks happen in the same thread). Basically, this is a deadlock:
```rs
let mutex = Mutex::new(())
let a = mutex.lock();
let b = mutex.lock(); // this line will never finish because `a` is still locked
```
As a rule of thumb, locks should be held for the shortest amount of time possible.

Azalea's ECS (the thing that contains pretty much everything about the world) is contained as a Mutex within every `Client`, so every function that accesses the world locks the ECS for a short instant. This includes `bot.eye_position()`.


Anyways, all that being said, I don't actually know what would cause that code to deadlock. The backtrace mentions the `eye_position` call in your code and an internal system in Azalea called `update_entity_chunk_positions`, but those two functions shouldn't conflict. I put the code you included in a bot and it does work as expected for me, every bot in the swarm walks towards the blocks and mine them.

The one thing that seems suspicious to me, though, is that while loop with an empty body. I think in certain cases this will actually cause a hang (not a deadlock, but still) if Tokio decides to run two tasks in the same thread.

I just pushed a commit that makes `bot.goto` an async function that waits for the pathfinding to finish, so if you update and remove that while loop hopefully your code will now work. In case you liked the old behavior though, the old goto function was renamed to start_goto (and if you want to keep your while loop you should add a `tokio::task::yield_now().await;` inside of it).

**Comment by manen** [comment]
thanks i updated and the deadlocks are fixed, but `wait_until_goto_target_reached` would sometimes panic because the tick broadcaster would lag

i just opened a pull request to stop it from panicking (#216)

**Comment by mat-1** [comment]
Not that I'm aware of Rust having fixed the issue, but is the segfault still happening?

**Comment by mat-1** [comment]
probably fixed by now
